### ISSUE TITLE
CreateAKS.ps1 Script Fails to Execute

### ISSUE THREAD

**Issue by limai-msk** [Sitecore/MVP-Site#10]
## Description
When running file CreateAKS.ps1 I get the following error:
`BadRequestError: Operation failed with status: 'Bad Request'. Details: Kubernetes Dashboard addon is deprecated for Kubernetes version >= 1.19.0.`

## Expected behavior
Running this powershell script should not yield errors.

## Steps To Reproduce
pwsh CreateAKS.ps1 -Region eastus -ResourceGroup sitecore -AksName sitecore -AcrName sitecoremvpdemo -AzureWindowsPassword XXXXXXXXXX

**Comment by robearlam** [comment]
Fixed, thanks for contributing!
