### ISSUE TITLE
Selecting Empty MVP Category throws error

### ISSUE THREAD

**Issue by jst-cyr** [Sitecore/MVP-Site#101]
## Description
When selecting no category (default drop-down option) an error is shown on the screen in an alert popup:

`"An error occured while saving your application. Please contact Sitecore Support"`

*(As a note: 'occured' is a typo and should be spelled 'occurred')*

I ran into this when purposefully trying to break it by selecting something, proceeding to the next step, then coming back and attempting to clear it out. I have not tested a flow where I select nothing initially.

## Expected behavior

I would expect that if the data model requires a value that the form is set to require the field entry and does not allow the user to proceed (or attempt a save of the form) with an empty value.

## Steps To Reproduce

1. Go to your application (/Application)
2. Make sure to agree to marketing messaging on the Welcome step
3. On the 'Category' step, select a category (any value)
4. Press "Next" to proceed to the Personal stage
5. Press "Previous" to return to the Category stage
6. Change the drop-down to the empty 'default' select option in the drop-down.
7. Press the "Next" button. Error displays.

## Possible Fix

I would suggest doing a validation on the drop-down to ensure a value is selected.

## Your Environment

* Browser Name and version: Chrome
* Operating System and version (desktop or mobile): Desktop
* Docker Version: N/A

## Screenshots
![image](https://user-images.githubusercontent.com/4146192/141012907-a34cafb1-2842-42cb-b297-c4ad17809630.png)

**Comment by lentalex627** [comment]
Category is now a required field and the application cannot be continued without selecting from the dropdown.  

![image](https://user-images.githubusercontent.com/4459003/141139576-df843e44-2a70-46eb-b7a9-c5446f2dbd47.png)
