### ISSUE TITLE
Placeholder text for Mentor field has a typo

### ISSUE THREAD

**Issue by jst-cyr** [Sitecore/MVP-Site#102]
## Description
On the Personal stage, there is a field for Mentor. The placeholder text reads "mentore". This appears to be a typo.

## Expected behavior
I would expect this to say something like "mentor name" or "mentor's full name"

## Steps To Reproduce

1. Go to '/Application'
2. Process your application to the Personal stage
3. On the Personal Information form, ensure the Mentor field is 'empty' so that placeholder text displays.

## Possible Fix
`mentor name` as a replacement text could work.

## Your Environment

* Browser Name and version: Chrome
* Operating System and version (desktop or mobile): Desktop
* Docker Version: N/A

## Screenshots
![image](https://user-images.githubusercontent.com/4146192/141013821-21efd9d5-9ab8-41ea-8473-0c3ebfc36dbb.png)

**Comment by robearlam** [comment]
Fixed in #98
