### ISSUE TITLE
Green check marks being displayed next to empty fields on Objectives stage

### ISSUE THREAD

**Issue by jst-cyr** [Sitecore/MVP-Site#106]
## Description
After stepping through the Application form to the Socials stage, I went back and noticed a green checkmark next to empty fields on the Objectives stage that I do not believe were there the first time through the form.

## Expected behavior
The green checkmark should be obvious as to what it indicates, and if indicating a 'saved value' should not be used when no value has been provided.

## Steps To Reproduce

1. Go to '/Application'
2. Advance your form to the Socials stage without entering any new values on Personal/Objectives stages
3. Press 'Previous' to go back to Objectives stage
4. Green checkmarks are shown.

## Your Environment

* Browser Name and version: Chrome
* Operating System and version (desktop or mobile): Desktop
* Docker Version: N/A

## Screenshots
![image](https://user-images.githubusercontent.com/4146192/141016143-ee6e7dfc-af30-48c3-bed7-d9c468ef922d.png)

**Comment by lentalex627** [comment]
These fields are marked as required now based on the requirements doc that was provided.  If you try to continue without filling them out, it will result in a red exclamation mark.  Once there is a value in place, a green checkmark will appear to let you know it is valid.

![image](https://user-images.githubusercontent.com/4459003/141140018-dd7606a1-575d-497e-bdcf-8e3292bde87f.png)
![image](https://user-images.githubusercontent.com/4459003/141140041-98f945aa-574c-489d-9ed6-ddaff9b5868e.png)
