### ISSUE TITLE
Community Profiles checkbox is not validated

### ISSUE THREAD

**Issue by jst-cyr** [Sitecore/MVP-Site#107]
## Description
The checkbox label on the Community Profiles stage reads: `By providing the above information I understand and agree that my community contribution via the above channels may be shared with Sitecore Feeds, SitecoreLink, and other Sitecore Community projects.`

This implies that a user must accept this in order to proceed. Proceeding forward does not block it, and changing stages changes the text to 'green' (which implies that I have accepted it or that this is a good state).

Also, the text reads as if the providing of the information is the agreement, not clicking the checkbox. Is the checkbox necessary at all? Or is it optional and somebody can opt out? If the latter, then the text needs to be updated.

## Expected behavior
This should be validated that it has been selected, if it is mandatory. 
If it is not mandatory and an applicant can opt out, then the text should be updated to reflect that "By clicking on this checkbox, I agree that my community contributions...".

## Steps To Reproduce

1. Go to /Application
2. Advance your application to the Socials stage
3. Press 'Previous' to return to the previous step (Objectives)
4. Press 'Next' to return to the 'Socials' stage
5. The checkbox label will display in green.
6. Press "Next" to advance
7. No validation is done of the checkbox

## Screenshots

![image](https://user-images.githubusercontent.com/4146192/141017238-25d9fc53-c467-45c2-b529-8113c5299412.png)

**Comment by mrtamasvarga** [comment]
This is a optional field, does not require validation. 

I have updated the wording to be more accurate: https://github.com/Sitecore/MVP-Site/commit/89d3baf4b10b499d45d8b34baf387cd4d1cb0863
