### ISSUE TITLE
No length validation on text fields

### ISSUE THREAD

**Issue by jst-cyr** [Sitecore/MVP-Site#109]
## Description
On the Socials stage of the Application, I put in a value for Stack Exchange that was over 1 million characters. Not only was it not validated, it also seems to have saved correctly. This seems like an easy attack vector for somebody to overflow storage or raise storage billing by dropping in high-volume text directly into the database.

## Expected behavior
Fields should have character length requirements and should be validated on the form client-side and server-side. Form should not advance and save extremely large values.

## Steps To Reproduce

1. Go to '/Application'
2. Advance to a stage with a text field. I used Stack Exchange field on the Socials stage
3. Create an incredibly large value in something like Notepad++
4. Copy to the field.
5. Advance the form.
6. No error is shown, advances correctly.
6. Return back to the stage.
7. Value seems to be stored. Copy/pasting out to Notepad++ shows full value, not trimmed value.

## Possible Fix
Field validator for length, along with updates to the labels to indicate limits to the user.

**Comment by joshuahover** [comment]
Hi @mrtamasvarga  - can you please let us know what you would like to limit the characters to? Once we get these details for the form, we can get this added in.

**Comment by mrtamasvarga** [comment]
All single line text should be no more than 256 characters, and textarea/multi line texts should be limited to 2000 characters.

**Comment by robearlam** [comment]
This is now closed as the repository is archived.

This has already been addressed in the new repository.
