### ISSUE TITLE
No validation of javascript or HTML injection

### ISSUE THREAD

**Issue by jst-cyr** [Sitecore/MVP-Site#110]
## Description
Text fields are not checking for stripping out HTML or JavaScript. I was able to put in several values that were saved without any errors or stripping. I am not sure if it is being encoded/decoded, but this is usually considered an attack vector. I cannot see what is stored on the backend right now, but that should be checked to see what impact it has on the editor instance, and also what impact it would have to the display version of the application.

## Expected behavior
JavaScript and HTML should not be accepted or should be stripped before saving to the database.

## Steps To Reproduce

1. Go to /Application
2. Advance to the Socials stage
3. Enter JavaScript value into the Github field. Ex: `javascript:alert('Yolo!');`
4. Enter HTML into the Twitter field. Ex:`<iframe src="https://twitter.com/StCyrThoughts">This should be fun</iframe>`
5. Press 'Next' button to advance
6. No validation is done, values appear to be saved

## Screenshots
![image](https://user-images.githubusercontent.com/4146192/141020019-2ec0bb64-2421-4ee7-b267-3044cbf2167e.png)

**Comment by robearlam** [comment]
This is now closed as the repository is archived.

This has already been addressed in the new repository.
