### ISSUE TITLE
Add Google Analytics Tag

### ISSUE THREAD

**Issue by robearlam** [Sitecore/MVP-Site#121]
There are currently no GA tags on the site, these need adding

**Comment by mrtamasvarga** [comment]
<script async src="https://www.googletagmanager.com/gtag/js?id=G-BHQTXWTDRH"></script>
<script>
  window.dataLayer = window.dataLayer || [];
  function gtag(){dataLayer.push(arguments);}
  gtag('js', new Date());

  gtag('config', 'G-BHQTXWTDRH');
</script>
