### ISSUE TITLE
Set up redirects for the MVP lists

### ISSUE THREAD

**Issue by mrtamasvarga** [Sitecore/MVP-Site#122]
## Description
The old website had listing of MVPs, but the new one has a search which is a great improvement, but the old links do not work anymore.

## Possible Fix
Need redirects for the following URLs to the search page:
https://mvp.sitecore.com/mvps -> https://mvp.sitecore.com/Search
https://mvp.sitecore.com/mvps/2021 -> https://mvp.sitecore.com/Search?fc_personyear=2021
https://mvp.sitecore.com/mvps/2020 -> https://mvp.sitecore.com/Search?fc_personyear=2020
https://mvp.sitecore.com/mvps/2019 -> https://mvp.sitecore.com/Search?fc_personyear=2019
https://mvp.sitecore.com/mvps/2018 -> https://mvp.sitecore.com/Search?fc_personyear=2018
https://mvp.sitecore.com/mvps/2017 -> https://mvp.sitecore.com/Search?fc_personyear=2017
https://mvp.sitecore.com/mvps/2016 -> https://mvp.sitecore.com/Search?fc_personyear=2016
https://mvp.sitecore.com/mvps/2015 -> https://mvp.sitecore.com/Search?fc_personyear=2015
https://mvp.sitecore.com/mvps/2014 -> https://mvp.sitecore.com/Search?fc_personyear=2014
https://mvp.sitecore.com/mvps/2008 -> https://mvp.sitecore.com/Search?fc_personyear=2008

**Comment by ahmed-ae** [comment]
this is fixed
