### ISSUE TITLE
Dropdown list for country includes both United States and USA

### ISSUE THREAD

**Issue by georgechang** [Sitecore/MVP-Site#125]
## Description
The dropdown list for "Country/Region/Territory" on Step 3 "Personal" includes values for both "United States" and "USA" which is redundant.

## Expected behavior
Only one of "United States" or "USA" should appear

## Steps To Reproduce
1. Go to Step 3 "Personal"
2. Click on "Country/Region/Territory" dropdown
3. Scroll down to "United States"
4. See "United States" with "USA" right below it.

## Possible Fix
Remove the "USA" option and normalize previous submissions to use "United States" where "USA" was used.

## Your Environment
* Browser Name and version: Edge 97
* Operating System and version (desktop or mobile): Windows 11 desktop
* Docker Version: N/A

## Screenshots

![image](https://user-images.githubusercontent.com/3603261/141697596-aa9dd1cc-db78-4831-b7f4-fb7d05bc9982.png)

**Comment by robearlam** [comment]
Fixed.
