### ISSUE TITLE
An error occured while creating your application.  Please contact Sitecore Support.

### ISSUE THREAD

**Issue by dnstommy** [Sitecore/MVP-Site#126]
On step 1, click begin application. 

<img width="604" alt="2021-11-14_18-57-59" src="https://user-images.githubusercontent.com/3902020/141704132-b6494396-2f19-4993-81cb-2c505a6fa313.png">

POST call is made to https://mvp.sitecore.com/submitStep1.

Response is:

`responseText: "An error occured while creating your application.  Please contact Sitecore Support."
success: false`

Browser then shows message.

<img width="448" alt="2021-11-14_18-55-03" src="https://user-images.githubusercontent.com/3902020/141704092-019b58b6-2322-465f-a293-2c32ec3aa052.png">

**Comment by robearlam** [comment]
Hi @dnstommy,

We had an issue on the site around this time which is fixed now. I can see your application, can you try again and see if it's working for you now?

Cheers!

**Comment by dnstommy** [comment]
@robearlam This is resolved. Thank you for the help.
