### ISSUE TITLE
Rendering host not resolving aliases

### ISSUE THREAD

**Issue by mrtamasvarga** [Sitecore/MVP-Site#153]
## Description
Search is an alias for Directory, but https://mvp.sitecore.com/Search returns Page Not Found

## Expected behavior
https://mvp.sitecore.com/Search shows content or redirects to https://mvp.sitecore.com/Directory

**Comment by sebastiantecsi** [comment]
Redirects have to be added to the code, nothing complicated.
Before that, @mrtamasvarga  can you confirm that in Sitecore Search item was renamed to Directory?

**Comment by mrtamasvarga** [comment]
Correct, the Search item was renamed to Directory and added Search as an alias to the item
![image](https://user-images.githubusercontent.com/23522600/146333491-b38b3f54-6475-4074-89f6-7b0f47df3be0.png)

**Comment by sebastiantecsi** [comment]
@mrtamasvarga , I have wrote extra code in order to have rendering host to resolve aliases https://github.com/Sitecore/MVP-Site/pull/159

**Comment by robearlam** [comment]
Closed in #159
