### ISSUE TITLE
Multiple Search facets aren't being applied correctly.

### ISSUE THREAD

**Issue by robearlam** [Sitecore/MVP-Site#158]
## Description
When selecting > 1 search facet, they aren't being applied correctly. e.g. when applying the following facets: https://mvp.sitecore.com/Directory?fc_personyear=2021&fc_personaward=Strategy

We are seeing results coming back for MVP's who don't have a 2021 Strategy award, but have received a strategy award in previous years.

## Expected behaviour
The facts should both be applied correctly.

**Comment by ahmed-ae** [comment]
I can work on this one

**Comment by ahmed-ae** [comment]
The problem is that we split Award into two facets (Year and category) , A potential solution for this can be to have drill down like facets, for example

[ ] 2022
     [ ] Technology
     [ ] Strategy
     [ ] Commerce
     [ ] AMBASSADOR
     [ ] Lifetime
[ ] 2021
     [ ] Technology
     [ ] Strategy
     [ ] Commerce
     [ ] AMBASSADOR
     [ ] Lifetime
[ ] 2020
     [ ] Technology
     [ ] Strategy
     [ ] Commerce
     [ ] AMBASSADOR
     [ ] Lifetime

@mrtamasvarga @robearlam  would this work?

**Comment by darjimaulik** [comment]
Still see the same. 
https://mvp.sitecore.com/Directory?fc_personyear=2022&fc_personaward=Technology&pg=3

**Comment by sebastiantecsi** [comment]
@robearlam I have made a fix, backend fix, for this bug https://github.com/Sitecore/MVP-Site/pull/166
I have not altered the visual part as @ahmed-ae suggested, as that will increase quite a lot the left part that contains the area of the facets.

cc @mrtamasvarga

**Comment by robearlam** [comment]
The PR from @sebastiantecsi has been deployed and people can now apply multiple facets.

@ahmed-ae, I dont think we need the FE changes or we would end up with too many facets to choose from

Closing this now.
