### ISSUE TITLE
Add a Country Facet 

### ISSUE THREAD

**Issue by nabilorfali** [Sitecore/MVP-Site#169]
## Is your feature request related to a problem? Please describe.
Can't filter the list by country 

## Describe the solution you'd like
Add a country facet in the searchable dropdown component to the left pane, so the user can either pick the country from the list or start typing with a real-time list filter.

**Comment by robearlam** [comment]
This functionality was added in #165

Not released to prod yet as we need a content population action to happen first. I'll leave this open so we can track when that happens.

**Comment by robearlam** [comment]
Data updated happened and this is now live.
