### ISSUE TITLE
 Cannot create container for service id: create .: volume name is too short, names should be at least two alphanumeric characters

### ISSUE THREAD

**Issue by alexksharma** [Sitecore/MVP-Site#17]
## Description
Getting bellow error while firing \up.ps1

Starting mvp-site_mssql_1 ... done
Creating mvp-site_cd_1    ... error
Creating mvp-site_id_1    ...

Creating mvp-site_id_1    ... error

ERROR: for mvp-site_id_1  Cannot create container for service id: create .: volume name is too short, names should be at least two alphanumeric characters

ERROR: for cd  Cannot create container for service cd: create .: volume name is too short, names should be at least two alphanumeric characters

ERROR: for id  Cannot create container for service id: create .: volume name is too short, names should be at least two alphanumeric characters
ERROR: Encountered errors while bringing up the project.
Waiting for CM to become available...
Invoke-RestMethod : Unable to connect to the remote server
At C:\Solutions\MVP-Site\up.ps1:26 char:19
+ ...   $status = Invoke-RestMethod "http://localhost:8079/api/http/routers ...
+                 ~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~
    + CategoryInfo          : InvalidOperation: (System.Net.HttpWebRequest:HttpWebRequest) [Invoke-RestMethod], WebException
    + FullyQualifiedErrorId : WebCmdletWebResponseException,Microsoft.PowerShell.Commands.InvokeRestMethodCommand

## Expected behavior
for cd  Cannot create container for service cd: create .: volume name is too short, names should be at least two alphanumeric characters.

## Steps To Reproduce

1. Fire \up.ps1

## Your Environment

* Browser Name and version:
* Operating System and version (desktop or mobile): Win 10 XP Pro
* Docker Version: Latest

## Screenshots
![image](https://user-images.githubusercontent.com/14735090/104830800-34e36580-58a8-11eb-93d3-ff5606f719d3.png)

**Comment by robearlam** [comment]
Did the suggestion from @djsmith fix this? Can we close the issue?

**Comment by robearlam** [comment]
Closed due to lack of activity

**Comment by joseamneto** [comment]
This happened to me once, when the init was not being executed passing the correct parameters
Ex: re-run and the issue will be fixed
.\init.ps1 -InitEnv -LicenseXmlPath C:\license\license.xml -AdminPassword b

**Comment by arthurbai** [comment]
still happend,what caused this issue?

PS D:\MVP-Site-main\MVP-Site> .\init.ps1 -InitEnv -LicenseXmlPath D:\license.xml -AdminPassword b
Preparing your Sitecore Containers environment!
Importing SitecoreDockerTools...
Generating Traefik TLS certificate...
The local CA is already installed in the system trust store! 👍
Note: Firefox support is not available on your platform. ℹ️


Created a new certificate valid for the following names 📜
 - "*.sc.localhost"

Reminder: X.509 wildcards only go one level deep, so this won't match a.b.sc.localhost ℹ️

The certificate is at "./_wildcard.sc.localhost.pem" and the key at "./_wildcard.sc.localhost-key.pem" ✅

It will expire on 22 June 2024 🗓

Adding Windows hosts file entries...
Populating required .env file values...
Done!
PS D:\MVP-Site-main\MVP-Site> .\up.ps1
工具“sitecore.cli”(版本“4.0.0”)已还原。可用的命令: sitecore

还原成功。
error while interpolating services.cd.mem_limit: failed to cast to expected type: strconv.ParseInt: parsing "4GB": invalid syntax
D:\MVP-Site-main\MVP-Site\up.ps1 : Container build failed, see errors above.
所在位置 行:1 字符: 1
+ .\up.ps1
+ ~~~~~~~~
    + CategoryInfo          : NotSpecified: (:) [Write-Error], WriteErrorException
    + FullyQualifiedErrorId : Microsoft.PowerShell.Commands.WriteErrorException,up.ps1

error while interpolating services.mvp-rendering.mem_limit: failed to cast to expected type: strconv.ParseInt: parsing "2GB": invalid syntax
Waiting for CM to become available...
Invoke-RestMethod : 无法连接到远程服务器
所在位置 D:\MVP-Site-main\MVP-Site\up.ps1:47 字符: 19
+ ...   $status = Invoke-RestMethod "http://localhost:8079/api/http/routers ...
+                 ~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~
    + CategoryInfo          : InvalidOperation: (System.Net.HttpWebRequest:HttpWebRequest) [Invoke-RestMethod]，WebException
    + FullyQualifiedErrorId : WebCmdletWebResponseException,Microsoft.PowerShell.Commands.InvokeRestMethodCommand

**Comment by joseamneto** [comment]
hi @arthurbai try the configurations below and let me know
On Docker , go to Settings compare the Checked and unchecked boxes
![image](https://user-images.githubusercontent.com/17772339/159509116-0d93157c-c4fb-412f-992e-9503785f861f.png)

Also check "docker Engine tab" 
![image](https://user-images.githubusercontent.com/17772339/159509256-e2f45191-51d6-4c4f-98a2-4b119ab7bdc6.png)

**Comment by quachnguyen** [comment]
Hi @Joseamneto 

I got the same issue 
![image](https://user-images.githubusercontent.com/128512/160220795-33124d53-61be-4c2f-9455-fd814529468b.png)
Here is my Docker's settings
![image](https://user-images.githubusercontent.com/128512/160220809-7837c19a-6a8a-4679-89dd-649b9365331b.png)

Do you have any idea?

**Comment by joseamneto** [comment]
hi @quachnguyen  ,if you were able to overcome the issue of the topic ": parsing "4GB": invalid syntax" and you are seeing only the issue that you present
I would recommend the instructions on the link 
[section "#4 Container “XXXXXXX” is unhealthy"]( https://errorcotidianam.wordpress.com/2021/09/14/sitecore-docker-common-issues-on-installation/ )
