### ISSUE TITLE
Pull photos from the Commuity Portal for the MVP Profiles as an additional option

### ISSUE THREAD

**Issue by mrtamasvarga** [Sitecore/MVP-Site#175]
Currently we use Gravatar to display the MVP profile photos. Some people might not want to sign up for Gravatar, so would be great to provide an option to use the Commuity Portal photos at the MVP profile.

Also there should be a switch if someone would prefer not to have a photo.

**Comment by sebastiantecsi** [comment]
@mrtamasvarga,

Is there an easy way to access photos from Sitecore Community Portal based on an email address? Similar as is for Gravatar?

/sebastian

**Comment by mrtamasvarga** [comment]
I think this feature makes sense if we have a profile for the MVPs, where they can not only associate their Community Portal, but other things, like their Twitter, LinkedIn and where they can choose to use the default image.

As soon as they provide us their Community ID than we can easily pull their photo and we can make this feature available.

**Comment by navancommits** [comment]
Although I created a gravatar profile, can't see it get picked in the mvp page... i noticed that my email hash in the mvp profile is totally different from what I see in my gravatar public url although I use the same email address... I would prefer this to be a field in Sitecore that way, the user can enter their gravatar public url  and just display image from the public url....

**Comment by mrtamasvarga** [comment]
It seems that the email address is case sensitive for the gravatar.

**Comment by robearlam** [comment]
Closed in #189
