### ISSUE TITLE
Searching for a specific user with first and last name still returns multiple results

### ISSUE THREAD

**Issue by darjimaulik** [Sitecore/MVP-Site#176]
## Description

I am searching for a specific user with the first name and last name. 

## Expected behavior

When I am providing specific search parameters, it should return only the person matching the complete search result. 

## Steps To Reproduce

1. Go to 'https://mvp.sitecore.com/Directory'
2. From the searchbox,, search for any MVP example - Maulik, you will find 2 results.
3. Now search with full name, First name and last name example - Maulik darji. This should give me a single result.  
4. But, It is showing results for 2 Maulik.

Link - https://mvp.sitecore.com/Directory?q=john%20west should return only John west but it shows 9 different persons.

**Comment by robearlam** [comment]
This is now closed as the repository is archived.

This has already been addressed in the new repository.
