### ISSUE TITLE
Facet count incorrect

### ISSUE THREAD

**Issue by rollewp** [Sitecore/MVP-Site#178]
## Description
The number next to the facet and results are two different numbers

## Expected behavior
Facet counts should match result count

## Steps To Reproduce
Navigate to https://mvp.sitecore.com/Directory?fc_personyear=2022&fc_personaward=Strategy&pg=1
See that facet count is 41 and actual results are 31

## Your Environment
Latest chrome on windows desktop

**Comment by k10con** [comment]
also true here where there are no results, facet count is 5 but there are no results
https://mvp.sitecore.com/Directory?q=&fc_personyear=2022&fc_personaward=%7CCloud

**Comment by robearlam** [comment]
Closed as this repository is being archived.

This has been addressed in the new repository.
