### ISSUE TITLE
Syntax error in RichTextContent.cshtml  

### ISSUE THREAD

**Issue by sebastiantecsi** [Sitecore/MVP-Site#179]
## Description
In RichTextContent.cshtml content that comes from Sitecore is wrapped around a p element
But the content that is coming from Sitecore is already wrapped around a p element or contains other elements inside.
The p element cannot contain [block-level elements](https://www.w3.org/TR/html401/struct/global.html#block-inline) (including [P](https://www.w3.org/TR/html401/struct/text.html#edef-P) itself) from https://www.w3.org/TR/html401/struct/text.html#h-9.3.1

## Possible Fix

Change `<p class="content">` with a div that has proper class style.

## Your Environment

* Browser Name and version: Chrome

**Comment by robearlam** [comment]
Closed as this repository is being archived.

This has been addressed in the new repository.
