### ISSUE TITLE
Create an MVP profile page

### ISSUE THREAD

**Issue by mrtamasvarga** [Sitecore/MVP-Site#183]
a.	From the search results link to the individual pages (MVP profiles)
b.	MVP awards are presented as badges
c.	Gravatar (or similar) solution to display profile photos
d.	Optionally link to Twitter, LinkedIn, Community and StackExchange profiles
e.	Display MVP podcast episode, see https://github.com/Sitecore/MVP-Site/issues/181

**Link**: 
https://github.com/Sitecore/MVP-Site/wiki/MVP-Requirements#mvp-edit-profile

**Comment by robearlam** [comment]
Closed as this repository is being archived.

This has been addressed in the new repository.
