### ISSUE TITLE
Documentation for setting up with OKTA

### ISSUE THREAD

**Issue by michaellwest** [Sitecore/MVP-Site#190]
I was going through the readme to setup the MVP site locally. Would you be able to provide a simple guide (screenshots) of what settings you expect with OKTA for a new developer account?

**Comment by michaellwest** [comment]
This article gave me some clue as what to do: https://www.linkedin.com/pulse/implement-okta-sitecore-federated-authentication-part-meng-han-li-1d

**Comment by navancommits** [comment]
then, there is this blog :) https://navansitecorenotes.blogspot.com/2021/12/how-to-setup-okta-for-sitecore.html

**Comment by michaellwest** [comment]
@navancommits Perhaps you can submit a PR with details you learned from your post.

**Comment by robearlam** [comment]
Closed as this repository is being archived.

This has been addressed in the new repository.
