### ISSUE TITLE
Create a "place" to show all the MVP logos and badges

### ISSUE THREAD

**Issue by mrtamasvarga** [Sitecore/MVP-Site#194]
Using the logos and badges listed on the Wiki https://github.com/Sitecore/MVP-Site/wiki/MVP-Badges we would need a place to show them. Could be part of the Aubout Us page or a dedicated page linked from the About Us page for everyone to see and download them. 

If needed we can add different file formats (EPS, JPG, etc.)

**Comment by cheeto-bandito** [comment]
@mrtamasvarga Have you considered leveraging digital credentials (such as Credly) to supplement the MVP awards?  This could be one way to manage the badges.  Here's an example of all of Microsoft's badges:

https://www.credly.com/organizations/microsoft-certification/badges

**Comment by mrtamasvarga** [comment]
@cheeto-bandito we have looked at Acclaim/Credly before but they could not provide the same functionality what we are looking for besides costing thousands of dollars. Even Microsoft has their own "directory" besides offering the Credly badges: https://mvp.microsoft.com/en-US/MvpSearch

**Comment by robearlam** [comment]
Closed as this repository is being archived.

This has been addressed in the new repository.
