### ISSUE TITLE
Directory Page: Type-Ahead Suggester for Keyword Search

### ISSUE THREAD

**Issue by cheeto-bandito** [Sitecore/MVP-Site#195]
Suggester functionality helps a user find their intended result even faster when using keyword search.  Sitecore even has some good documentation on how to configure this functionality in Solr:

https://doc.sitecore.com/xp/en/developers/102/platform-administration-and-architecture/using-solr-auto-suggest.html

![image](https://user-images.githubusercontent.com/76630589/160011568-63e1d547-3a14-4833-b298-a7bab6d42f83.png)

1. Primary Use Case: Suggest by MVP Name
2. Secondary Use Case: Suggest by facet - this means that if I want to search for all MVPs in India, I can type in 'India' and selecting the suggestion would automatically select the India facet.

**Comment by robearlam** [comment]
Closed as this repository is being archived.

This has been addressed in the new repository.
