### ISSUE TITLE
Directory Page Shows Odd Numbers Instead Of Even 

### ISSUE THREAD

**Issue by VadzimPapko** [Sitecore/MVP-Site#199]
## Description
By default the Directory Page shows 20 MVPs divided by 3 columns (desktop mode) on each raw. That means last raw contains only two MVPs instead of three.

![image](https://user-images.githubusercontent.com/3023032/167647996-e8a060f9-fcd0-4df5-a94d-b23d8e42e5c9.png)

## Expected behavior
The Directory Page shows 21 MVPs per each page and the last raw (desktop mode) contains three items instead of two.

## Steps To Reproduce
1. Go to [Directory](https://mvp.sitecore.com/Directory)
2. Observe you can see 20 results instead of 21
3. In Desktop mode the last raw contains two items instead of three

![image](https://user-images.githubusercontent.com/3023032/167630323-6f137476-886b-425f-9650-480ec1c6ae24.png)

## Possible Fix
Replace default page size from 20 to 21

**Comment by aliew** [comment]
Hi @VadzimPapko . I was hoping if I was able to assist you with addressing this issue?

**Comment by VadzimPapko** [comment]
Hi @aliew , I am not sure I got you. Did you resolve this issue?

**Comment by robearlam** [comment]
Fixed a pushed.
