### ISSUE TITLE
Confusing setting name `Sitecore__ExternalCdUrl` in CM configuration

### ISSUE THREAD

**Issue by sshushliapin** [Sitecore/MVP-Site#205]
There is setting `Sitecore__ExternalCdUrl: "${CD_HOST}"` in the [docker-compose.override.yml](https://github.com/Sitecore/MVP-Site/blob/603097850b7d0c116fb33ad27ef81b940e8f8f28/docker-compose.override.yml#L214) (and [k8s specs](https://github.com/Sitecore/MVP-Site/blob/603097850b7d0c116fb33ad27ef81b940e8f8f28/k8s/specs/staging/cm.yaml#L181)) which looks strange. Is it named "CdUrl" and placed in CM config. In fact, that's `hostName` setting from the [website registration](https://github.com/Sitecore/MVP-Site/blob/603097850b7d0c116fb33ad27ef81b940e8f8f28/src/Project/Sugcon/platform/App_Config/Include/Project/Project.Sugcon.config#L7).

Wouldn't it be better to avoid CD in the setting name, e.g. ` Sitecore__ExternalUrl` or `Sitecore__PublicUrl`.
BTW, shouldn't it point to "${CM_HOST}" on CM?

**Comment by robearlam** [comment]
Closed as this repository is being archived.

This has been addressed in the new repository.
