### ISSUE TITLE
Being able to edit an MVP application

### ISSUE THREAD

**Issue by GoranHalvarsson** [Sitecore/MVP-Site#208]
## Description
To be able to edit an MVP application

## Expected behavior
Edit an MVP application

## Steps To Reproduce
Edit button is missing :-(

## Your Environment

* Browser Name and version:
* Operating System and version (desktop or mobile):
* Docker Version:

**Comment by robearlam** [comment]
Hi @GoranHalvarsson,

The current MVP application is being run from the new repo here: https://github.com/Sitecore/XM-Cloud-Introduction

Can you provide a bit more information about the issue as well, you should be able to edit your application. You should also be able to re-open your application using the "Revoke" button after you've submitted?

Cheers!

**Comment by GoranHalvarsson** [comment]
Thank you, 
I did not know that the Revoke button is the "edit" button :-)
