### ISSUE TITLE
Date Range Selection while adding contribution

### ISSUE THREAD

**Issue by khushboosorthiya** [Sitecore/MVP-Site#209]
## Is your feature request related to a problem? Please describe.
I would like to have an option select date range when we add a contribution. We do some of the activities through out the year. For example, Sitecore Mentorship Program, Leading Sitecore User Group, etc. In this scenario, it is too much to add an entry for all the things we do as part of these activities. It would be good to have an option to select a date range in this scenarios.

**Comment by robearlam** [comment]
Hi @khushboosorthiya ,

The current MVP application is being run from the new repo here: https://github.com/Sitecore/XM-Cloud-Introduction, this repository will be archived in the coming weeks. 

Can you please post your issue in that repository so it can be tracked there?

Thanks

**Comment by khushboosorthiya** [comment]
Sure. Thanks @robearlam

**Comment by robearlam** [comment]
Closed as this repository is being archived.

This has been addressed in the new repository.
