### ISSUE TITLE
Cannot change MVP Type after it has been selected, or after revoking the application

### ISSUE THREAD

**Issue by Amir818** [Sitecore/MVP-Site#211]
## Description
Once an application has been saved, you can no longer change the MVP Type from the dropdown.  This was seen in both applications that have not been fully submitted as well as applications that were revoked and resubmitted.

## Expected behavior
User should be able to change the MVP Type from the dropdown.

## Steps To Reproduce
1. Create an application. 
2. Choose an MVP Type.
3. Proceed to next step.
4. Exit application
5. Go back to application and attempt to change MVP type. Proceed to next step.
6. Go to previous step, and MVP Type will revert to the original selection.
The same can be observed if application is fully submitted, then revoked.

## Possible Fix
Ensure that MVP Type is updated after it has been changed.

## Your Environment

* Browser Name and version: Chrome latest
* Operating System and version (desktop or mobile):  MacOS 12.6

**Comment by robearlam** [comment]
Closed as this repository is being archived.

This has been addressed in the new repository.
