### ISSUE TITLE
Unable to run the Azure DevOps pipeline: "An image does not exist locally with the tag" while pushing to ACR 

### ISSUE THREAD

**Issue by Hardik2003** [Sitecore/MVP-Site#25]
## Description
While importing the project in Azure DevOps is successful, the pipeline fails to run when pushing the built images to ACR in the build stage itself.  This is the error message:

"C:\Program Files\Docker\docker.exe" push <acr_login_name>/mvp-cd:10.1.0-ltsc2019
The push refers to repository [<acr_login_name>/mvp-cd]
An image does not exist locally with the tag: <acr_login_name>/mvp-cd
##[error]The process 'C:\Program Files\Docker\docker.exe' failed with exit code 1
Finishing: Push Images with Latest Tag

## Expected behaviour
I'm running the project in Azure DevOps and the pipeline should execute successfully without any errors

## Steps To Reproduce
1. Import the project in Azure DevOps
2. Populate the environment variables as needed which includes the Azure subscription service endpoint, the ACR endpoints amongst others
3. Run the pipeline and it fails when pushing the images to ACR

## Possible Fix
It seems to me that the images are not being tagged to properly push them to ACR. They should be tagged as follows:
<acr_login_name>/mvp-cd (the same for others)

## Your Environment
* Azure Devops

## Screenshots
<img width="850" alt="Screenshot 2021-06-04 at 5 09 02 PM" src="https://user-images.githubusercontent.com/8852710/120795990-d4537d00-c557-11eb-927f-30b901632dcd.png">
<img width="858" alt="Screenshot 2021-06-04 at 5 09 11 PM" src="https://user-images.githubusercontent.com/8852710/120796010-d87f9a80-c557-11eb-900f-2cd5c2bf865d.png">

**Comment by robearlam** [comment]
It feels like you have an issue with your Azure DevOps variables, can you post in what variables you have defined? (Free to blank out any values as required)

**Comment by Hardik2003** [comment]
Hi @robearlam - I guess I figured out the issue. I was missing the MVP_DOCKER_REGISTRY variable. I had to populate that variable with my ACR login URL in order for the push to work successfully.

My initial thought was that the value should be "mvpsitev2.azurecr.io" but that is incorrect, right?

**Comment by robearlam** [comment]
Correct, you need to populate the MVP_DOCKER_REGISTRY variable with the URL of your ACR instance. This can be retrieved from the Azure Portal.

**Comment by robearlam** [comment]
Hi @Hardik2003, are we ok to close this off now?

**Comment by Hardik2003** [comment]
Hi @robearlam - Sure. We can definitely close this issue.

**Comment by rnareshr** [comment]
Hi @robearlam - we are unable to push image with Latest Tag to ACR ?same similar above error. please provide some solution
How we can populate MVP_DOCKER_REGISTRY variable with the URL of your ACR instance. Please assist me with screenshot. 
 
Advance thanks

![push](https://user-images.githubusercontent.com/87079673/124783022-5cb3ac00-df62-11eb-996f-791c9e1b71c8.JPG)

**Comment by rnareshr** [comment]
Hi @Hardik2003, 
We are unable to push image with Latest Tag to ACR ? same similar above error. please provide some solution
How we can populate MVP_DOCKER_REGISTRY variable with the URL of your ACR instance. Please assist me with screenshot.

Advance thanks

**Comment by Hardik2003** [comment]
Hi @rnareshr - You need to populate the MVP_DOCKER_REGISTRY variable with the URL of your ACR instance (It can be found in the Azure portal) here: 
https://github.com/Sitecore/MVP-Site/blob/master/.env#L28

**Comment by Sharanabasava212** [comment]
Hi @Hardik2003- We are getting error like Deploy Application Specifications please assist me fix this issue

**Comment by rnareshr** [comment]
![deploy](https://user-images.githubusercontent.com/87079673/124889319-9af9ab80-dff4-11eb-8406-717283af0017.JPG)

**Comment by rnareshr** [comment]
> Hi @Hardik2003,
> We are unable to push image with Latest Tag to ACR ? same similar above error. please provide some solution
> How we can populate MVP_DOCKER_REGISTRY variable with the URL of your ACR instance. Please assist me with screenshot.
> 
> Advance thanks


> Hi @rnareshr - You need to populate the MVP_DOCKER_REGISTRY variable with the URL of your ACR instance (It can be found in the Azure portal) here:
> https://github.com/Sitecore/MVP-Site/blob/master/.env#L28

Thank you Hardik 
just i have missed the '/' in the MVP_DOCKER_REGISTRY .env file
![env](https://user-images.githubusercontent.com/87079673/124889757-05125080-dff5-11eb-9464-0e69b94c0268.JPG)

**Comment by rnareshr** [comment]
Hi @Hardik2003 

we are using free trial subscription for azure, we are new for Sitecore and AKS, after add the MVP docker registry value we able to push the image in ACR .
Now we are doing Deploy stage in the deploy stage we got error on Deploy Application Specifications task 
In the ingress.yml file I have attached image please assist me what is the value of below host ?

 - $(STAGING_HOST) = ?
    - $(STAGING_ID_HOST) = ?
    - $(STAGING_CM_HOST)= ?
    - $(STAGING_CD_HOST) = ?
Please give some solution to fix the issue.

Advance thanks 

![ingress](https://user-images.githubusercontent.com/87079673/124891144-553de280-dff6-11eb-8baf-26fbd3bb9e81.JPG)





![ingress](https://user-images.githubusercontent.com/87079673/124890126-5b7f8f00-dff5-11eb-9414-ba720a3c04de.JPG)

**Comment by rnareshr** [comment]
Hi @Hardik2003 

 I have added below value in build variable .build successful but iam not sure the below value is  right r wrong please confirm the value.

$(STAGING_HOST) =mvp.sc.localhost
$(STAGING_ID_HOST) =mvp-id.sc.localhost
$(STAGING_CM_HOST)=mvp-cm.sc.localhost
$(STAGING_CD_HOST) = mvp-cd.sc.localhost

final deseialize content is failed  please find the attached screenshot. Please assist me 

Now 
![final deserialize](https://user-images.githubusercontent.com/87079673/124910009-b969a200-e008-11eb-9ba3-b225e5e287a5.JPG)

Many thanks

**Comment by rnareshr** [comment]
Hi @Hardik2003  

Above issue with Nuget feed, so I have provided nuget feed variable (https://sitecore.myget.org/F/sc-packages/api/v3/index.json) now above issue is fixed 

Next issue with  Deserialize Content
dotnet sitecore login --client-credentials true --auth $(ID_SERVER_URL) --cm $(CM_URL) --allow-write true --client-id "MVP_Automation" --client-secret "$(SITECORE_MVP_IDENTITY_SECRET)"

Please let me know below value 
$(ID_SERVER_URL) =?
$(CM_URL) =?
$(SITECORE_MVP_IDENTITY_SECRET) =?


Thanks

**Comment by rnareshr** [comment]
Hi @robearlam,

Please help us to complete Sitecore deployment in AKS.

**Description**
We need few clarification on Sitecore-AKS-CICD azurepipline.yaml file

As per my knowledge, we don't need to do any Sitecore setup in azure portal. Please correct me if I am wrong .

https://github.com/Sitecore/MVP-Site  
We have used Azurepipline.yaml file to build and deploy in AKS.

fyi. we don't know the value for docker compose file args, so we removed this line dockerComposeFileArgs: '$(DOCKER_COMPOSE_ARGS)' in docker build and push task 

**Stage 1**
CI Build - We are able to build and push image successful 

**Stage 2** 
CD Deploy - we are able to deploy successful with below value 

1st Deploy application specification (DAS) task failed in deploy stage so I have added below value in Azure build variable after adding value task (DAS) is successful 
but I am not sure the below value is right r wrong ? please conform the value.

STAGING_CD_HOST = mvp-cd.sc.localhost   ?
STAGING_CM_HOST =  mvp-cm.sc.localhost ?
STAGING_HOST = mvp.sc.localhost ?
STAGING_ID_HOST = mvp-id.sc.localhost ?

**Stage 3** 
 'Deserialize_Content_to_Staging'
Here we able Install Sitecore CLI

After installation we need to Authenticate the ID, here it's failing due to wrong URL and secret.  
Below value we have added in build pipeline please let us know exact value for this its will help for us.

CM_URL   =   https://mvp-cm.sc.localhost/sitecore/login  ???
ID_SERVER_URL = https://mvp-id.sc.localhost ???
SITECORE_MVP_IDENTITY_SECRET  = Siteconidentityserver.MVP.local ???

**Error**
Logging into ID Server
Error discovering identity provider. Perhaps the authority hostname, https://mvp-id.sc.localhost/, is not valid or it is not serving OpenID metadata (/.well-known/openid-configuration).
Push Content
Environment default was not defined. Use the login command to define it

Please find the attachment for Build Log.
[logs_338.zip](https://github.com/Sitecore/MVP-Site/files/6791573/logs_338.zip)


Many Thanks

**Comment by Hardik2003** [comment]
Hi @rnareshr - Your values:

$(STAGING_HOST) =mvp.sc.localhost
$(STAGING_ID_HOST) =mvp-id.sc.localhost
$(STAGING_CM_HOST)=mvp-cm.sc.localhost
$(STAGING_CD_HOST) = mvp-cd.sc.localhost

are correct. They can be anything though. Its purely a matter of choice and should be named appropriately. 

Regarding the last step of content deserialization, even I was facing an issue there and thus happened to build another pipeline with another codebase. To my knowledge, they should be as follows:

CM_URL = mvp-cm.sc.localhost
ID_SERVER_URL = mvp-id.sc.localhost
SITECORE_MVP_IDENTITY_SECRET = <Is there a secret created or populated before as part of secrets generation for native sitecore installation?>

If they don't work, @robearlam will have to assist us with that.

**Comment by rnareshr** [comment]
> Hi @rnareshr - Your values:
> 
> $(STAGING_HOST) =mvp.sc.localhost
> $(STAGING_ID_HOST) =mvp-id.sc.localhost
> $(STAGING_CM_HOST)=mvp-cm.sc.localhost
> $(STAGING_CD_HOST) = mvp-cd.sc.localhost
> 
> are correct. They can be anything though. Its purely a matter of choice and should be named appropriately.
> 
> Regarding the last step of content deserialization, even I was facing an issue there and thus happened to build another pipeline with another codebase. To my knowledge, they should be as follows:
> 
> CM_URL = mvp-cm.sc.localhost
> ID_SERVER_URL = mvp-id.sc.localhost
> SITECORE_MVP_IDENTITY_SECRET = <Is there a secret created or populated before as part of secrets generation for native sitecore installation?>
> 
> If they don't work, @robearlam will have to assist us with that.

Hi @Hardik2003 

Thank you for your reply and support
