### ISSUE TITLE
Error ID_SERVER_URL Logging into ID Server Error discovering identity provider. Perhaps the authority hostname, https://mvp-id.sc.localhost/, is not valid or it is not serving OpenID metadata (/.well-known/openid-configuration). Push Content

### ISSUE THREAD

**Issue by rnareshr** [Sitecore/MVP-Site#26]
Hi Team,

@robearlam @KoenHeye @markvanaalst @GuidovTricht @jst-cyr @GuidovTricht @jbluemink @navancommits 

Please help us to complete Sitecore deployment in AKS.

We need few clarification on Sitecore-AKS-CICD azurepipline.yaml file

As per my knowledge, we don't need to do any Sitecore setup in azure portal. Please correct me if I am wrong .

https://github.com/Sitecore/MVP-Site

we are using free trial subscription for azure portal.we have configured new resources group ACR & AKS in Azure portal 

We have used docker/Azurepipline.yaml file to build and deploy in AKS.

fyi. we don't know the value for docker compose file args, so we removed this line dockerComposeFileArgs: '$(DOCKER_COMPOSE_ARGS)' in docker build and push task

Stage 1
CI Build - We are able to build and push image successful

Stage 2
CD Deploy - we are able to deploy successful with below value

1st Deploy application specification (DAS) task failed in deploy stage so I have added below value in Azure build variable after adding value task (DAS) is successful
but I am not sure the below value is right r wrong ? please conform the value.

STAGING_CD_HOST = mvp-cd.sc.localhost ?
STAGING_CM_HOST = mvp-cm.sc.localhost ?
STAGING_HOST = mvp.sc.localhost ?
STAGING_ID_HOST = mvp-id.sc.localhost ?

Stage 3
'Deserialize_Content_to_Staging'
Here we able Install Sitecore CLI

After installation we need to Authenticate the ID, here it's failing due to wrong URL and secret.
Below value we have added in build pipeline please let us know exact value for this its will help for us.

CM_URL = https://mvp-cm.sc.localhost/sitecore/login ???
ID_SERVER_URL = https://mvp-id.sc.localhost ???
SITECORE_MVP_IDENTITY_SECRET = Siteconidentityserver.MVP.local ???

Error
Logging into ID Server
Error discovering identity provider. Perhaps the authority hostname, https://mvp-id.sc.localhost/, is not valid or it is not serving OpenID metadata (/.well-known/openid-configuration).
Push Content
Environment default was not defined. Use the login command to define it

Please find the attachment for Build Log.
logs_338.zip

Many Thanks

**Comment by robearlam** [comment]
Hi @rnareshr,

These build execute on an Azure DevOps build agent, so you will need to have a real URL that can be resolved for each of your Sitecore instances, along with a valid HTTPS certificate for each as well.

You can't use *.localhost and self generated certs as they are not available on the Azure DevOps build agent.

Thanks,
Rob

**Comment by rnareshr** [comment]
Hi @robearlam ,
 
Thanks for your reply 

1. First thing we are new to sitecore and AKS.
2. While using Hosted agent we are able to build and deploy in AKS 
3. Now when we say its Azure DevOps Agent does it imply a self hosted agent? 
4. If it is a self hosted agent then should we setup docker SQL visual studio & Sitecore?
5. Are there any alternatives to deploy to Publish content (ID_Server_URL , CM_URL) using hosted agent?.
6. If we assume we are using self hosted agent, then what all would we need to build, push and deploy publish content. Then accordingly we will install the necessary in self hosted agent and do all that is required.

Thanks & Regards,
Naresh

**Comment by robearlam** [comment]
Hi @rnareshr,

This topic is far too broad to be covered via a Github issue. The issue system is here to log problems with the source being shared, what you need is guidance for how to configure your automated build for Sitecore.

You state that you're new to both Sitecore & AKS, so you're going to have a lot of work ahead to get up to speed on both of them. I would recommend joining the [Sitecore Community Slack](https://sitecore.chat/), there are a series of very active channels covering not only general Sitecore questions, and also focusing on running Sitecore on Docker/AKS. Slack is far better suited to asking these types of broad questions that benefit from discussion.

I'm going to close this issue now and mark it as out of scope.

Thanks,
Rob
