### ISSUE TITLE
Solution does not illustrate how to overwrite hostName or targetHostName in config files.

### ISSUE THREAD

**Issue by gh-joliver** [Sitecore/MVP-Site#27]
## Is your feature request related to a problem? Please describe.

I don't understand how to configure a site's properties such as hostName, targetHostname, or database on a per-environment basis while using AKS.

## Describe the solution you'd like

I would like this solution to illustrate or explain how this is done.

## Additional information

I apologize if this is in the repo, but I've looked and I don't see it.

A hostname of "mvp-cm.sc.localhost" is hardcoded into App_Config/Include/Project.MvpSite.config. This file is baked into the resulting CM and CD container images.  I do not see anything in the build process that would change this for a release build, and I do not see anything configured to pump this in as an environment variable. 

How do you take the resulting images and use them in an AKS environment as opposed to a local docker one? What are the options for handling this in the real world?

I understand this may not strictly be necessary for the MVP Site itself, but it would be nice if one of the examples addressed this topic.

**Comment by robearlam** [comment]
Agree we need to include this, I added a task in to the project planner to track this from now, closing this issue.
