### ISSUE TITLE
404 page needs styling

### ISSUE THREAD

**Issue by robearlam** [Sitecore/MVP-Site#55]
Currently the 404 page is unstyled, It should match the rest of the site.

**Comment by navancommits** [comment]
Not sure how to assign this to me, anyway, will work on this from tomorrow, if I run into issues, will update here so that someone else can take over....

**Comment by navancommits** [comment]
Ready for review - https://github.com/Sitecore/MVP-Site/pull/160

**Comment by navancommits** [comment]
Merged to main.... this is closed now...
