### ISSUE TITLE
Add example Azure Devops Variables to repo

### ISSUE THREAD

**Issue by limai-msk** [Sitecore/MVP-Site#9]
## Is your feature request related to a problem? Please describe.

When reading the file: https://github.com/Sitecore/MVP-Site/blob/master/docker/azure-pipelines.yml, I see many references to variables that are not maintained in code. I would like to deploy this MVP site to learn but am not able to because I don't have examples to follow for how to set up my Azure Devops account that meets the pipeline requirements.

Example of variables being referenced:
- DOCKER_COMPOSE_ARGS
- SITECORE_PUBLIC_NUGET_FEED
- AZURE_SUBSCRIPTION
- AKS_SERVICE_ENDPOINT

Even if working values for each are not able to be provided, a single file that has all the variables needed with placeholder or example fake values, would be great.

## Describe the solution you'd like

Include a azure-variables.yml file along with the azure-pipeline.yml file

**Comment by robearlam** [comment]
Agree this needs to be somewhere, I don't like the idea of including it in the repo though as it could lead people to believe that is where the values need to be populated. Instead I've added a page to the wiki covering these variables.

https://github.com/Sitecore/MVP-Site/wiki/Azure-DevOps
