### ISSUE TITLE
Add a "Sign Up" button to the Application/Intro page

### ISSUE THREAD

**Issue by mrtamasvarga** [Sitecore/MVP-Site#91]
## Is your feature request related to a problem? Please describe.
If you don't have Sitecore ID you cannot log in.

## Describe the solution you'd like
Add a "Sign Up" button to the Application/Intro page
Sign up page here: https://www.sitecore.com/account/signup

**Comment by robearlam** [comment]
This is now closed as the repository is archived.

This has already been addressed in the new repository.
