### ISSUE TITLE
Search page has too many apostrophes

### ISSUE THREAD

**Issue by jst-cyr** [Sitecore/MVP-Site#92]
## Description
On the MVP search page (/Search) the title reads `Sitecore MVP's'`. In this case, there should be only one at most, but likely none as to pluralize you would write it as MVPs (since this is not a possessive usage). 

## Expected behavior
 In this case, there should be only one apostrophe at most, but likely none as to pluralize you would write it as MVPs (since this is not a possessive usage). 

## Steps To Reproduce

1. Go to '/Search' by clicking on the Search link in the header
2. See title of the page

## Possible Fix
This should likely be a content change, no code fix required

## Your Environment

* Browser Name and version: Chrome 95..4638.69
* Operating System and version (desktop or mobile): Windows 10 Enterprise Version	10.0.18363 Build 18363
* Docker Version:

**Comment by mrtamasvarga** [comment]
See the commit https://github.com/Sitecore/MVP-Site/commit/d40da03bf4e55ff497e564231e83a85fd86ff7d6
