### ISSUE TITLE
Enter key does not submit search

### ISSUE THREAD

**Issue by jst-cyr** [Sitecore/MVP-Site#93]
## Description
On the /Search page, hitting "Enter" while focused in the search box does not submit the search.

## Expected behavior
While typing in your search keywords, if Enter is pressed, I would expect the search to submit and results to be shown.

## Steps To Reproduce

1. Go to '/Search' by clicking the Search option in the menu
2. Type in the search box 'aaron'
3. Hit the 'enter' or 'return' key on your keyboard
4. Results are not updated

## Possible Fix
My guess is that the search keyword box needs to be set as a default form for the page?

## Your Environment

* Browser Name and version: Chrome 95..4638.69
* Operating System and version (desktop or mobile): Windows 10 Enterprise Version	10.0.18363 Build 18363
* Docker Version:

**Comment by sebastiantecsi** [comment]
Hi @jst-cyr,
I've made a fix here, https://github.com/Sitecore/MVP-Site/pull/168
cc @mrtamasvarga @robearlam

**Comment by jst-cyr** [comment]
Thank you @sebastiantecsi ! @mrtamasvarga , can you identify who you would like to review the PR?

**Comment by robearlam** [comment]
Reviewed and deployed.
