### ISSUE TITLE
Search page should populate title from Sitecore

### ISSUE THREAD

**Issue by mrtamasvarga** [Sitecore/MVP-Site#95]
## Is your feature request related to a problem? Please describe.
Title of the page should come from Sitecore

## Describe the solution you'd like
Populate <p class="top">
and <h1 class="static">
from the Sitecore item /sitecore/content/MvpSite/Home/Search "Page Components"

**Comment by sebastiantecsi** [comment]
@mrtamasvarga, the issue looks a bit cryptic. Can you please update it?
Thank you.

**Comment by robearlam** [comment]
This is now closed as the repository is archived.

This has already been addressed in the new repository.
