### ISSUE TITLE
MVP Application form step 1 - Blank MVP category

### ISSUE THREAD

**Issue by markvanaalst** [Sitecore/MVP-Site#96]
## Description
Leaving category blank results in error

## Expected behavior
Form validation message saying that the category is required

## Steps To Reproduce
1. Go to Application
3. Leave category field blank
2. Click on Next

## Possible Fix
Enabling form validation?

## Your Environment
https://mvp.sitecoredemo.com/Application
Microsoft Edge Version 95.0.1020.44 (Official build) (64-bit)
Windows 10 

## Screenshots
![image](https://user-images.githubusercontent.com/1365552/140936396-7c1ac7f5-9bc2-403f-8393-755b3f47c672.png)

**Comment by lentalex627** [comment]
PR created 
https://github.com/Sitecore/MVP-Site/pull/98
