### ISSUE TITLE
No form validation on MVP application form

### ISSUE THREAD

**Issue by markvanaalst** [Sitecore/MVP-Site#97]
## Description
With the exception of the Confirmation and Submission page there seems to be no form validation on any of the form fields. I am able to go through all steps without entering anything in the form fields. Might be related to #96 

## Expected behavior
Fields that are required (marked with a *) should either give a message or have some visual reminder that those are required  when navigation through all the steps.

## Steps To Reproduce
1. Go to MVP application
2. Select category
3. Click on Next (2x)
3. No form field validation, next step is loaded

## Your Environment
https://mvp.sitecoredemo.com/Application
Microsoft Edge Version 95.0.1020.44 (Official build) (64-bit)
Windows 10

**Comment by lentalex627** [comment]
PR created 

https://github.com/Sitecore/MVP-Site/pull/98
